@startuml


skinparam componentStyle uml2
left to right direction

title Diagrama de Componentes - SGO

actor Cliente

[API REST] as API

Cliente --> API : HTTP

' =====================================================
' INTERFACES
' =====================================================

interface "ICompetições" as ICompeticoes
interface "IAtletas" as IAtletas
interface "IPaises" as IPaises
interface "ILocais" as ILocais
interface "IInscricoes" as IInscricoes
interface "IResultados" as IResultados
interface "IRelatorios" as IRelatorios


together {

node "Docker - Competições" {

    package "Serviço Competições" {

        component "Competições" as Competicoes

        interface "IDBCompeticoes" as IDBC

        database "PostgreSQL\nCompetições DB" as DBCompeticoes

        Competicoes -- ICompeticoes
        Competicoes --( IDBC :TCP/IP
        DBCompeticoes -- IDBC
    }
}

node "Docker - Atletas" {

    package "Serviço Atletas" {

        component "Atletas" as Atletas

        interface "IDBAtletas" as IDBA

        database "PostgreSQL\nAtletas DB" as DBAtletas

        Atletas -- IAtletas
        Atletas --( IDBA :TCP/IP
        DBAtletas -- IDBA
    }
}

}


together {

node "Docker - Países" {

    package "Serviço Países" {

        component "Países" as Paises

        interface "IDBPaises" as IDBP

        database "PostgreSQL\nPaíses DB" as DBPaises

        Paises -- IPaises
        Paises --( IDBP :TCP/IP
        DBPaises -- IDBP
    }
}

node "Docker - Locais" {

    package "Serviço Locais" {

        component "Locais" as Locais

        interface "IDBLocais" as IDBL

        database "PostgreSQL\nLocais DB" as DBLocais

        Locais -- ILocais
        Locais --( IDBL :TCP/IP
        DBLocais -- IDBL
    }
}

}


together {

node "Docker - Inscrições" {

    package "Serviço Inscrições" {

        component "Inscrições" as Inscricoes

        interface "IDBInscricoes" as IDBI

        database "PostgreSQL\nInscrições DB" as DBInscricoes

        Inscricoes -- IInscricoes
        Inscricoes --( IDBI :TCP/IP
        DBInscricoes -- IDBI
    }
}

node "Docker - Resultados" {

    package "Serviço Resultados" {

        component "Resultados" as Resultados

        interface "IDBResultados" as IDBRes

        database "PostgreSQL\nResultados DB" as DBResultados

        Resultados -- IResultados
        Resultados --( IDBRes :TCP/IP
        DBResultados -- IDBRes
    }
}

}
node "Docker - Relatórios" {

    package "Serviço Relatórios" {

        component "Relatórios" as Relatorios

        interface "IDBRelatorio" as IDBR

        database "PostgreSQL\nRelatórios DB" as DBRelatorios

        Relatorios -- IRelatorios
        Relatorios --( IDBR :TCP/IP
        DBRelatorios -- IDBR
    }
}

' =====================================================
' API REQUER INTERFACES
' =====================================================

API --( ICompeticoes : REST
API --( IAtletas : REST
API --( IPaises : REST
API --( ILocais : REST
API --( IInscricoes : REST
API --( IResultados : REST
API --( IRelatorios : REST

' =====================================================
' SERVIÇOS REQUEREM INTERFACES
' =====================================================

Competicoes --( IAtletas
Competicoes --( IPaises
Competicoes --( ILocais

Inscricoes --( ICompeticoes

Resultados --( ICompeticoes
Resultados --( IAtletas

Relatorios --( IResultados
Relatorios --( IPaises

@enduml